### ISSUE TITLE
Update the Login System to integrate Organizations

### ISSUE THREAD

**Issue by DannyPeck** [CS450-ECE461/fall2016-group2-adminportal#14]
The Login System will now need to know which Organization the user wishes to login too. The Login will need to be updated to reflect this change.

**Comment by eburgun** [comment]
Why will the login system need to know which organization the user wishes to login too? Aren't the organizations a property of the user already? You can't exactly have one admin be the admin for multiple organizations. If I'm misunderstanding the point of this please let me know.

**Comment by DannyPeck** [comment]
The issue this is addressing is that you have to think of this from the perspective of multiple organizations.  You should be able to have someone with the same username on different organizations but not the same username within an organization.  Therefore, in order to login to that user, you would need to be logging into that organization as well.

**Comment by eburgun** [comment]
Fair enough. If that is the case though, we might consider using a different aspect to log in than the username. There are a few reasons that it would be worth our time to switch to something like email instead. When looking at the app from a user's perspective the more pieces of information needed to log in the bigger of a pain in the ass it is too login. Thus we want to keep it as simple as possible. Also since the admin is the one creating the user with the user's email chances are they will be using the user's company email which would be unique to them and yet allow for multiple users to have the same username. eburgun at company A will have email eburgun@companyA.com, eburgun at company B will have email eburgun@companyB.com, yet both could have username eburgun. The fact that pretty much every company in the world has already solved this issue within their internal system it would make sense to take advantage of that. Unfortunately, this means we'd have to go back and change what's already there. But it prevents us from adding another aspect of complexity to the login process. It's essentially the exact same code and we just have to check the email address and not the username.

**Comment by DannyPeck** [comment]
I think that that is a great idea and a wonderful solution to that problem!  Do you think this is something we should bring up with the client or simply decide?  Either way, I think this is the most elegant solution.

**Comment by eburgun** [comment]
Did the client ever even mention anything about how they needed to be able to log in? You've had more contact with them than I have. If not i'd say just implement it that way otherwise let's ask.

**Comment by DannyPeck** [comment]
I don't believe so, I am going to change it so that login is based on a unique email address.
